using System;
using System.Text.RegularExpressions;

namespace WebRequestMask.Core;

// generated by Qwen3.7-Plus, reviewed by y0soro
//
// see https://www.tampermonkey.net/documentation.php?locale=en&q=include#meta:match
//     https://developer.chrome.com/docs/extensions/mv2/match-patterns
// for syntax and spec
internal class UserScriptMatch
{
    private readonly Regex _regex;

    /// <summary>
    /// Initializes a new instance of the <see cref="UserScriptMatch"/> class.
    /// </summary>
    /// <param name="pattern">The @match pattern (e.g., "*://*.example.com/*")</param>
    public UserScriptMatch(string pattern)
    {
        if (string.IsNullOrWhiteSpace(pattern))
            throw new ArgumentException("Pattern cannot be null or empty.", nameof(pattern));

        // Parse the @match pattern syntax: <scheme>://<host><path>
        // Group 1: Scheme (*, http, https, file, ftp, urn)
        // Group 2: Host (*, *.<domain>, or <domain> with optional port)
        // Group 3: Path (starts with /, can contain *)
        var match = Regex.Match(pattern, @"^(\*|http|https|file|ftp|urn):\/\/([^\/]*)(\/.*)?$");

        if (!match.Success)
            throw new ArgumentException($"Invalid @match pattern format: {pattern}");

        string scheme = match.Groups[1].Value;
        string host = match.Groups[2].Value;
        string path = match.Groups[3].Success ? match.Groups[3].Value : "/";

        // 1. Scheme Regex
        // '*' matches both http and https
        string schemeRegex = scheme == "*" ? @"https?" : Regex.Escape(scheme);

        // 2. Host Regex
        // '*' matches any host. '*.' matches subdomains.
        string hostRegex = host == "*" ? @"[^/]*" : Regex.Escape(host).Replace(@"\*", @"[^/]*");

        // 3. Path Regex
        // '*' matches any characters in the path/query/fragment
        string pathRegex = Regex.Escape(path).Replace(@"\*", @".*");

        // Combine them.
        // Note: Scheme and Host are case-insensitive, Path is case-sensitive per spec.
        // We use inline regex modifiers (?i:...) and (?-i:...) to enforce this.
        string fullRegex = $"^(?i:{schemeRegex}://{hostRegex})(?-i:{pathRegex})$";

        _regex = new Regex(fullRegex, RegexOptions.Compiled);
    }

    /// <summary>
    /// Checks if the provided URL matches the @match pattern.
    /// </summary>
    public bool IsMatch(string url)
    {
        if (string.IsNullOrWhiteSpace(url))
            return false;

        // Normalize URL using Uri class to ensure it has a path (e.g. adds trailing slash to root domains)
        // This prevents "https://example.com" from failing against "https://example.com/"
        if (Uri.TryCreate(url, UriKind.Absolute, out Uri uri))
        {
            url = uri.AbsoluteUri;
        }

        return _regex.IsMatch(url);
    }
}
